import { readFileSync } from "node:fs";
import { createAccount, createClient } from "../frontend/node_modules/genlayer-js/dist/index.js";
import { studionet } from "../frontend/node_modules/genlayer-js/dist/chains/index.js";
import { TransactionStatus } from "../frontend/node_modules/genlayer-js/dist/types/index.js";
const text = readFileSync(new URL("../.env", import.meta.url), "utf8");
const env = Object.fromEntries(text.split(/\r?\n/).filter((line) => line.includes("=") && !line.trim().startsWith("#")).map((line) => { const i = line.indexOf("="); return [line.slice(0, i).trim(), line.slice(i + 1).trim()]; }));
const deployment = JSON.parse(readFileSync(new URL("../deployment.json", import.meta.url), "utf8"));
const account = createAccount(env.STUDIONET_PRIVATE_KEY);
const client = createClient({ chain: studionet, account, endpoint: "https://studio.genlayer.com/api" });
const address = deployment.contract_address;
const rounds = JSON.parse(String(await client.readContract({ address, functionName: "list_rounds" })));
const candidate = [...rounds].reverse().find((round) => round.status === "OPEN" && round.submissions?.some((submission) => ["SUBMITTED", "RETRYABLE"].includes(submission.status)));
if (!candidate) throw new Error("No active review candidate found");
const submission = candidate.submissions.find((item) => ["SUBMITTED", "RETRYABLE"].includes(item.status));
const hash = await client.writeContract({ address, functionName: "review_submission", args: [submission.id], value: 0n });
const receipt = await client.waitForTransactionReceipt({ hash, status: TransactionStatus.FINALIZED, interval: 3000, retries: 50 });
const after = JSON.parse(String(await client.readContract({ address, functionName: "get_round", args: [candidate.id] })));
const credits = JSON.parse(String(await client.readContract({ address, functionName: "get_account_credits", args: [account.address] })));
console.log(JSON.stringify({ roundId: candidate.id, submissionId: submission.id, hash, status: receipt.statusName ?? String(receipt.status), result: receipt.resultName ?? String(receipt.result), after, credits }, null, 2));
